credentials:
  usernames:
    admin:
      email: amazon@amazon.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: yeahmobi
      password: $2b$12$IV4WKDWOf2WsxJiWHJjd8e21bCHqeM5pGne0n9Ua6ar.LBnWwj/mK
cookie:
  expiry_days: 36000
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
    - amazon@amazon.com
